name: SSH to EC2

on:
  push:
    branches: [main]

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and run commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            if [ ! -d "learn-ci-cd" ]; then
              git clone https://github.com/Satnammeena2004/learn-ci-cd.git
            fi
            export PATH=$HOME/.nvm/versions/node/v22.17.1/bin:$PATH
            echo "======pwd========="
            pwd
            ls
            echo "======changing the directory========="
            cd learn-ci-cd
            echo "======after changing the directory========="
            pwd
            echo "======ls in learn-ci-cd========="
            ls
            echo "====== checking version of npm ========="
            $PATH
            echo "====== checking version of npm ========="
            npm -v
            echo "====== checking version of node ========="
            node -v
            git pull origin main
            npm install
            npm run build
            npm start
