name: SSH to EC2

on:
  push:
    branches: [main]

jobs:
  ssh:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2 and run commands
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            git clone  https://github.com/Satnammeena2004/learn-ci-cd.git
            cd learn-ci-cd
            ls
